[package]
name = "rd-dir"
version = "0.1.0"
edition = "2021"
description = "A tool to reading directories"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.1.0"
